source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target “Project BlackSky” do
pod 'AWSCore'
pod 'AWSAutoScaling'
pod 'AWSCloudWatch'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSElasticLoadBalancing'
pod 'AWSKinesis'
pod 'AWSLambda'
pod 'AWSMachineLearning'
pod 'AWSMobileAnalytics'
pod 'AWSS3'
pod 'AWSSES'
pod 'AWSSimpleDB'
pod 'AWSSNS'
pod 'AWSSQS'
pod 'AWSCognito'
pod 'LayerKit’
pod 'Atlas'
pod 'GoogleAPIClient/Calendar'
pod 'GTMOAuth2'
end